### ISSUE TITLE
God mode subclasses

### ISSUE THREAD

**Issue by tpd1864blake** [steven4547466/AdvancedSubclassing#1]
**Describe the bug**
Some subclasses have god mode without enabling god mode through remote admin or abilities

**To Reproduce**
1. This seems to happen with any subclass regardless of abilities or settings
2. Do something to hurt yourself, such as throwing a grenade at your feet, or jumping off the bridge

**Expected behavior**
You take grenade/fall damage unless you have the ImmuneFrag or Godmode abilities

**Screenshots**
N/A

**Console Logs**
[output.txt](https://github.com/steven4547466/AdvancedSubclassing/files/5210548/output.txt)

**Versioning**
 - AdvancedSubclassing Version (e.g. 1.0.0-pre013): 1.0.0-pre014
 - Exiled Version (e.g. 2.1.3): 2.1.3

**Additional context**
I think it has something to do with the get hurt event, maybe something is setting the damage to 0

**Comment by steven4547466** [comment]
I'll look into it. Can you show your config as well? (Ill add that to the template later)

**Comment by steven4547466** [comment]
Nevermind, I fixed it. 014 was the in-dev branch anyways. Here's the full 014 version: https://github.com/steven4547466/AdvancedSubclassing/releases/tag/1.0.0-pre014

**Comment by tpd1864blake** [comment]
Thank you
