### ISSUE TITLE
WaitSpawnWave

### ISSUE THREAD

**Issue by coco9515** [steven4547466/AdvancedSubclassing#13]
**Is your feature request related to a problem? Please describe.**
I would like some classes to not be able to spawn from the first spawn wave (as those are support classes). And we can't count reliably on the random factor to spawn them correctly.

**Describe the solution you'd like**
A new integer value "WaitSpawnWave" that would let us have some classes unable to spawn until X spawn have spawned.
A secondary bollean subvalue wcould be "OnlyCountingSameTeam", if true, that would only count the MTF spawns if the class is based on a MTF member and don't acount for the chaos spawns.

**Describe alternatives you've considered**
Another idea could be an additive chance for every spawn.
Start as the default spawn class (like 5%) and for every spawn, adds X%.
I would argue that this idea could be implemented WITH the "WaitSpawnWave" to be even better !

**Additional context**
N/A

**Comment by tpd1864blake** [comment]
There's a ”spawn_as” config that can be used to get that effect

**Comment by tpd1864blake** [comment]
Oh wait I read that wrong

**Comment by steven4547466** [comment]
This will be in the next pre-release. It was implemented with 3 different config options.
The boolean option is called `WaitForSpawnWaves` which is `false` by default. If you set this to true, you must have an integer option called `NumSpawnWavesToWait`. There is an optional string option called `WaitSpawnWaveTeam`, which defaults to `RIP`, which in this case means count all spawn waves. The strings value option will work with `CHI` and `MTF`
