### ISSUE TITLE
Immunity to 106 Teleport

### ISSUE THREAD

**Issue by coco9515** [steven4547466/AdvancedSubclassing#16]
**Is your feature request related to a problem? Please describe.**
```yml
roles_that_cant_damage:
- Scp106
```
That protect from the direct hit from 106 but not from the TP to the pocket dimension.

**Describe the solution you'd like**
An ability to not be TP to the pocket dimension.

**Describe alternatives you've considered**
Could be included in the "roles that can't damage: SCP106" but it would limit people, best to give options.

**Additional context**
N/A

**Comment by steven4547466** [comment]
[1.2.0-pre002](https://github.com/steven4547466/AdvancedSubclassing/releases/tag/1.2.0-pre002) should fix this, let me know if you still experience issues
