### ISSUE TITLE
More roles could escape ?

### ISSUE THREAD

**Issue by coco9515** [steven4547466/AdvancedSubclassing#19]
**Is your feature request related to a problem? Please describe.**
After seing this added to the changelog "You can now disable escaping by setting the value to the same as the role the player already has.". It makes me think about adding the possibility for subclasses to escape even when not scientists or class D.
My server would love to have guard flee to, for exemple.

**Describe the solution you'd like**
By using the already present "escapes_as:" value. "None" leaving the default behaviour, otherwise the player would escape and respawn as the specified class, depending if he is cuffed or not.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by steven4547466** [comment]
This will be added in pre004 for 1.2.0, I'll close this when I release that.
