### ISSUE TITLE
Quantity of Roles Requirement

### ISSUE THREAD

**Issue by coco9515** [steven4547466/AdvancedSubclassing#21]
**Is your feature request related to a problem? Please describe.**
I have no way to make certain class spawns based on the number of people having this (or another) role.

**Describe the solution you'd like**
Dictionary of role (and/or classes).
A boolean to swith between "Requirement" for the class to be available and "Bonus" that would give an <integer value> bonus to the "ChanceToGet" of this class.

**Describe alternatives you've considered**
N/A

**Additional context**
If SCP-173 naturally spawn, I would love to have a higher % for my 173 specialist to spawn.
If I have 5 or more classe D and no SCP-079; change one into SCP-079.

PS : I realized that's at least a part of what I asked for the "Linked class"; if what I proposed here can take into account both roles and classes, I guess that can work for both suggestion, no ?

**Comment by steven4547466** [comment]
I could do this for base game classes, but I can't do this for subclasses. The reason I can't tie it with subclasses is that they don't have a specific order they're given in, someone might get a role last that would increase the chances of another role spawning. I can look into doing it with a base game class, though.

**Comment by coco9515** [comment]
Even with the base game role, that would already be powerfull !

I had another idea where those "required" base could help, it's with the "escapes_as", it could lock the escape for the subclass as long as there are the selected roles still present - or with a boolean toggle, inverse it and make only able to escape while those role are present 🤔

**Comment by steven4547466** [comment]
I'll try to implement some type advanced escape rules like you described.

**Comment by steven4547466** [comment]
Implemented `spawn_parameters`. See [here](https://github.com/steven4547466/AdvancedSubclassing/releases/tag/1.2.0-pre012). Advanced escape rules will be set for next release.
