### ISSUE TITLE
More customization on escapes_as config

### ISSUE THREAD

**Issue by tpd1864blake** [steven4547466/AdvancedSubclassing#24]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be cool if you could set a few config options like health and stuff when you escaped (separate config for cuffed and uncuffed) to make some Scientists/Class-D more high-value and have more of a reason to escort them out over other people

**Describe alternatives you've considered**
N/A

**Additional context**
I am making a Scientist subclass called Facility Manager. It would be in Chaos Insurgency's best interest to escort them out instead of shooting them on sight, to add a unique gameplay twist. To create a reward for cuffing them out, I want to make it so they spawn as a Chaos Insurgent with a buff to their health.

**Comment by steven4547466** [comment]
If I implemented this, subclasses would override these options. However I can make it so you can set classes to only be given on escape and do this.

**Comment by steven4547466** [comment]
I forgot to close this when I implemented `OnlyGivenOnEscape` as a boolean option
