### ISSUE TITLE
New ability : Night Vision

### ISSUE THREAD

**Issue by coco9515** [steven4547466/AdvancedSubclassing#28]
**Is your feature request related to a problem? Please describe.**
I would like an unit capable to see in the dark (usefull during blackouts).

**Describe the solution you'd like**
A new ability should be the best way I guess.
Could have a command to toggle it on / off.

The idea is to reuse the Epsilon mod that have night vision and apply it to the whole screen in permanence.

**Describe alternatives you've considered**
The alternative would be less interesting, I think, would be sticking a light in permanence in front of the player.

**Additional context**
N/A

**Comment by steven4547466** [comment]
Unfortunately, this is client side and I am unable to do it
