### ISSUE TITLE
Command to forceclass as a sublcass.

### ISSUE THREAD

**Issue by Bonjemus** [steven4547466/AdvancedSubclassing#32]
**Is your feature request related to a problem? Please describe.**
There's no way to forceclass someone to a specific subclass which quite annoying for events.

**Describe the solution you'd like**
I would like to see a command which would look something like this :
`subclass [Player id/All] [Subclass name]`
Here's an exemple :
`subclass all test1`

   _- Sincerely Bonjemus_

**Comment by steven4547466** [comment]
That already exists. I can add an all option in the future https://github.com/steven4547466/AdvancedSubclassing/wiki/Remote-Admin-Commands
