### ISSUE TITLE
PryGates on all gates

### ISSUE THREAD

**Issue by coco9515** [steven4547466/AdvancedSubclassing#6]
**Is your feature request related to a problem? Please describe.**
I'm using the Custom Door Access plugin, and I used it to lock some gates that until now could be open by hand.
But if I use the PryGates ability, I still can't open them.

**Describe the solution you'd like**
That the PryGates ability can work on all gates IF they can't be open by hand.
Should be possible since 096 can actually pass those locked gates anyways.

Additionnally, could the locked behind keycard / reinforced doors (Like 106, Nuke Exterior or the checkpoints) be open too ?
As a secondary ability maybe or parametres to the PryGates ability.

**Describe alternatives you've considered**
Asking the Custom Door Access dev ?

**Additional context**
Outside 914, Gate A & B; there are the Exterior Gate & SCP-372 (GR-18 in light).

**Comment by steven4547466** [comment]
PryGates will now work on locked gates regardless of their security level in the next patch. But it still has no reason to need to work on unlocked gates that can be opened without a keycard.
