### ISSUE TITLE
Linked classed

### ISSUE THREAD

**Issue by coco9515** [steven4547466/AdvancedSubclassing#9]
**Is your feature request related to a problem? Please describe.**
A way to link classes; ex: I want a guard and a class D to spawn at 173 together.
For now, the only way is to give really high chances for both classes to spawn, but then it breaks the random factor as it would be always - I would like to keep that.

**Describe the solution you'd like**
Having a new parametre that make another class spawn, could be easily identified by the class name.
Could have another float options for chance to get the additional classes so it's not certain that we will have it.

**Describe alternatives you've considered**
Could be the opposite "can't spawn if class is not present" and the original "chance to get" will still work to avoid the 100% spawn all the time.

**Additional context**
N/A

**Comment by steven4547466** [comment]
I'll see if I can implement something like this.

**Comment by steven4547466** [comment]
I'll probably end up going the `can't spawn if class is not present` as linking classes is actually really difficult with how classes are evaluated. But I'll probably expand on this. Specifically it's probably going to be more of a `spawn_parameters` option that defines what must be true for the class to spawn including:
- Certain classes being present or not
- Certain # of players alive or dead, or a range of either or both
- Certain teams present, or not
- Certain # roles being present or not 
This is not final and is still difficult to implement, but I'll see if I can get it to work. **Some of these can only apply post game start.** As I stated in the other issue, trying to get present subclasses at the start of the round isn't the best idea as they might spawn, but just haven't yet.

**Comment by steven4547466** [comment]
Implemented as `spawn_parameters`. See [here](https://github.com/steven4547466/AdvancedSubclassing/releases/tag/1.2.0-pre012)
